# 7. Route (Expose App to Internet)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: rosa-poc
  name: app-route
spec:
  host: uat-hybridcloud.krungsri.com
  to:
    kind: Service
    name: app-service
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGTzCCBTegAwIBAgIQDT6ecM9kGjmLiSCb6tpwpDANBgkqhkiG9w0BAQsFADBZ
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
      aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjYw
      MjEyMDAwMDAwWhcNMjYwNTMxMjM1OTU5WjCBijELMAkGA1UEBhMCVEgxEDAOBgNV
      BAgTB0Jhbmdrb2sxETAPBgNVBAcTCFlhbiBOYXdhMS8wLQYDVQQKEyZCQU5LIE9G
      IEFZVURIWUEgUFVCTElDIENPTVBBTlkgTElNSVRFRDElMCMGA1UEAxMcdWF0LWh5
      YnJpZGNsb3VkLmtydW5nc3JpLmNvbTB2MBAGByqGSM49AgEGBSuBBAAiA2IABNna
      SC7G5np86P/GWTARF7WFPsm404voUxqDQjMJpj0HnfNs/+ztnmMD88iP1c6padU2
      5AaqbddraHHa8Ex7EDz1vuNe35Ia9Tz3ejUGx29HV1d1ZehKWAF883UiUs3BB6OC
      A40wggOJMB8GA1UdIwQYMBaAFHSFgMBmx9833s+9KTeqAx2+7c0XMB0GA1UdDgQW
      BBQYKHEzGgh8SrdYLEqF8jyAkrXIczAnBgNVHREEIDAeghx1YXQtaHlicmlkY2xv
      dWQua3J1bmdzcmkuY29tMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkwJwYIKwYBBQUH
      AgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCA4gw
      EwYDVR0lBAwwCgYIKwYBBQUHAwEwgZ8GA1UdHwSBlzCBlDBIoEagRIZCaHR0cDov
      L2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYy
      MDIwQ0ExLTEuY3JsMEigRqBEhkJodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vRGln
      aUNlcnRHbG9iYWxHMlRMU1JTQVNIQTI1NjIwMjBDQTEtMS5jcmwwgYcGCCsGAQUF
      BwEBBHsweTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMFEG
      CCsGAQUFBzAChkVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRH
      bG9iYWxHMlRMU1JTQVNIQTI1NjIwMjBDQTEtMS5jcnQwDAYDVR0TAQH/BAIwADCC
      AX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHYAlpdkv1VYl633Q4doNwhCd+nwOtX2
      pPM2bkakPw/KqcYAAAGcULAfOgAABAMARzBFAiAS5iYadkL2Dn8B6Ibrttzg3LhE
      lwpi6ZlEN+fCsNUfmwIhAOIA0HH0tA3LZv4o4aXq4SXBoMEL+WSfL4deLsKO49Rg
      AHUAFoMtq/CpJQ8P8DqlRf/Iv8gj0IdL9gQpJ/jnHzMT9foAAAGcULAfKQAABAMA
      RjBEAiA32hyUJ9TqaLtXdq1w8n1gR3PC9uwDDQAZD/VIj3RO1wIgGvj2VuQIDNPp
      HBpKzmir8j6wWXXbdCp8LnOdzZ8fyIUAdgBkEcRspBLsp4kcogIuALyrTygH1B41
      J6vq/tUDyX3N8AAAAZxQsB86AAAEAwBHMEUCIBrD/cdYS/rxFRK+6hV9GnFyfwUd
      fzgbO4RVutuQnQfPAiEAscGF/2fky6fR4somG6p6A+b70F3ecRV5R5aNvTu+z0Qw
      DQYJKoZIhvcNAQELBQADggEBAKtQD/LKNlDBsbiK6rB9nTLITlFX/C8cjx30lc+Z
      Xj4rS/ndWBbszDGjRH8vw2otFel1cUSTZscno9tkUipeFwrF9zClH5GVKcHzcU57
      jVTfnE1ChpvJ67K9se/xHhFlJAZGwPYLBbpkOHj5itzc2y5w+0O4L7hcMzE9DZvR
      Ak21xltj7U20730hY1VUQby+4QHluA7tjkurJvcO9hZLmbHDiMJnX321JmCU+G4q
      r8Kfv3R9RHHTWgcqOHSHwkEwPiMeapVMnBbYusy8fjCzuzQqvI8GZdP0WGrfvoxT
      C3UjrI025n2Hq1SgiYvBuZteUoop0/3kSM3bKe/v3mk0sx8=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MIGkAgEBBDAuDVTv57v3MrzFCKHtsvm/aiKtFA22KOa3fp4PIeRiRF0zX7QiRh6t
      VohqaaayqD+gBwYFK4EEACKhZANiAATZ2kguxuZ6fOj/xlkwERe1hT7JuNOL6FMa
      g0IzCaY9B53zbP/s7Z5jA/PIj9XOqWnVNuQGqm3Xa2hx2vBMexA89b7jXt+SGvU8
      93o1BsdvR1dXdWXoSlgBfPN1IlLNwQc=
      -----END EC PRIVATE KEY-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIEyDCCA7CgAwIBAgIQDPW9BitWAvR6uFAsI8zwZjANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
      MjAeFw0yMTAzMzAwMDAwMDBaFw0zMTAzMjkyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMzAxBgNVBAMTKkRpZ2lDZXJ0IEdsb2Jh
      bCBHMiBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBAMz3EGJPprtjb+2QUlbFbSd7ehJWivH0+dbn4Y+9lavyYEEV
      cNsSAPonCrVXOFt9slGTcZUOakGUWzUb+nv6u8W+JDD+Vu/E832X4xT1FE3LpxDy
      FuqrIvAxIhFhaZAmunjZlx/jfWardUSVc8is/+9dCopZQ+GssjoP80j812s3wWPc
      3kbW20X+fSP9kOhRBx5Ro1/tSUZUfyyIxfQTnJcVPAPooTncaQwywa8WV0yUR0J8
      osicfebUTVSvQpmowQTCd5zWSOTOEeAqgJnwQ3DPP3Zr0UxJqyRewg2C/Uaoq2yT
      zGJSQnWS+Jr6Xl6ysGHlHx+5fwmY6D36g39HaaECAwEAAaOCAYIwggF+MBIGA1Ud
      EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHSFgMBmx9833s+9KTeqAx2+7c0XMB8G
      A1UdIwQYMBaAFE4iVCAYlebjbuYP+vq5Eu0GF485MA4GA1UdDwEB/wQEAwIBhjAd
      BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdgYIKwYBBQUHAQEEajBoMCQG
      CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQAYIKwYBBQUHMAKG
      NGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RH
      Mi5jcnQwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
      L0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNybDA9BgNVHSAENjA0MAsGCWCGSAGG/WwC
      ATAHBgVngQwBATAIBgZngQwBAgEwCAYGZ4EMAQICMAgGBmeBDAECAzANBgkqhkiG
      9w0BAQsFAAOCAQEAkPFwyyiXaZd8dP3A+iZ7U6utzWX9upwGnIrXWkOH7U1MVl+t
      wcW1BSAuWdH/SvWgKtiwla3JLko716f2b4gp/DA/JIS7w7d7kwcsr4drdjPtAFVS
      slme5LnQ89/nD/7d+MS5EHKBCQRfz5eeLjJ1js+aWNJXMX43AYGyZm0pGrFmCW3R
      bpD0ufovARTFXFZkAdl9h6g4U5+LXUZtXMYnhIHUfoyMo5tS58aI7Dd8KvvwVVo4
      chDYABPPTHPbqjc1qCmBaZx2vN4Ye5DUys/vZwP9BFohFrH/6j/f3IL16/RZkiMN
      JCqVJUzKoZHm1Lesh3Sz8W2jmdv51b2EQJ8HmA==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
      MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
      b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
      2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
      1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
      q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
      tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
      vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
      BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
      5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
      1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
      NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
      Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
      8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
      pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
      MrY=
      -----END CERTIFICATE-----
