FROM mcr.microsoft.com/azure-sql-edge:latest

USER root
RUN mkdir -p /usr/config && \
    chown -R mssql:0 /usr/config && \
    chmod -R g=u /usr/config

WORKDIR /usr/config
COPY ./init-scripts/init.sql /usr/config/init.sql

# Allow the random OpenShift user to read/write to the config dir
RUN chown -R mssql:0 /usr/config && chmod -R g=u /usr/config

# Switch back to mssql user but ensure it's compatible
USER 10001 
CMD ["/opt/mssql/bin/sqlservr"]