FROM mcr.microsoft.com/azure-sql-edge:latest

USER root
RUN mkdir -p /usr/config
WORKDIR /usr/config

# Copy the init script and entrypoint
COPY ./init-scripts/init.sql /usr/config/init.sql
COPY ./entrypoint.sh /usr/config/entrypoint.sh
RUN chmod +x /usr/config/entrypoint.sh

RUN chown -R mssql /usr/config
USER mssql

# Start SQL Server with initialization
CMD ["/usr/config/entrypoint.sh"]